name: FaceLink
options:
  bundleIdPrefix: io.github.kmpfacelink
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    FRAMEWORK_SEARCH_PATHS:
      - $(inherited)
      - $(SRCROOT)/../kmp-facelink/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
    SWIFT_INCLUDE_PATHS:
      - $(inherited)
      - $(SRCROOT)/../kmp-facelink/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/KMPFaceLink.framework/Modules

targets:
  FaceLink:
    type: application
    platform: iOS
    sources:
      - path: FaceLink
    dependencies:
      - framework: ../kmp-facelink/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/KMPFaceLink.framework
        embed: false
    preBuildScripts:
      - name: Build KMP Framework
        script: |
          cd "$SRCROOT/.."
          ./gradlew :kmp-facelink:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
    info:
      path: FaceLink/Info.plist
      properties:
        NSCameraUsageDescription: "Face tracking requires camera access"
        UIRequiredDeviceCapabilities:
          - arkit
          - front-facing-camera
        UILaunchScreen: {}
